services:
  database:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: tarmac_fox
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local